### ISSUE TITLE
「TypeScript で"moduleResolution": "Node"は使わないほうがいい」でのmainフィールドに関しての説明について

### ISSUE THREAD

**Issue by sapphi-red** [shun-shobon/articles#1]
初めまして、https://blog.s2n.tech/articles/dont-use-moduleresolution-node という記事を読みました。
とてもわかりやすかったです！ 👍 

一点記事の中で不正確だと思われる記述がありましたので、ここで報告いたしします。

> 一つ注意したいのが、このフィールドは CommonJS でのみ使用され、ES Modules では使用されません。

と書かれていますが、ESMでもmainフィールドは基本使用されます。
これは[Node.jsのESMでのモジュール解決の仕様](https://nodejs.org/dist/latest-v18.x/docs/api/esm.html#resolver-algorithm-specification)の[`PACKAGE_RESOLVE`の11.内の6.](https://nodejs.org/dist/latest-v18.x/docs/api/esm.html#resolver-algorithm-specification:~:text=Otherwise%2C%20if%20packageSubpath,in%20packageURL.)が該当箇所です。

実際にその挙動は下の手順で確かめることができます。

1. https://github.com/sapphi-red-repros/esm-main-field-resolve をクローンする
1. `pkg` ディレクトリを開く
2. `npm i` を実行
3. `node index.js` を実行

---

#### 補足:

ESMでもmainフィールドは使用されますが、正確にはパッケージのトップレベルにある`package.json`のもののみ使用されます。(CJSではパッケージのトップレベルでない`package.json`も使用される)
これは[CJSのモジュール解決の仕様](https://nodejs.org/dist/latest-v18.x/docs/api/modules.html#all-together)での`LOAD_AS_DIRECTORY`内で、パッケージ直下かどうかにかかわらず`package.json`のmainフィールドを利用する処理があることからわかります。
こちらのほうはかなり細かい話なので記事では触れなくても問題ないと思います。

**Comment by shun-shobon** [comment]
@sapphi-red 
大変丁寧なご指摘ありがとうございます！
自分の方でも確認したところ，再現できたため https://github.com/shun-shobon/articles/commit/52e36b331fd5b3f1df1cebec49d8c7447ccc24ab にて修正しました！ご確認いただけると幸いです。

**Comment by sapphi-red** [comment]
確認いたしました。問題ないと思います！
